const bank={
 topics:[
  ["什麼是 InSAR？","地球科學"],["SBAS-InSAR 的原理","地球科學"],["GNSS 可以量測什麼？","地球科學"],["地層下陷形成原因","地球科學"],["為什麼地下水超抽會造成地層下陷？","地球科學"],["MODFLOW 是什麼？","地球科學"],["GMT 可以做哪些地圖？","地球科學"],["地震規模與震度差別","地球科學"],["什麼是震源機制解（Beach Ball）？","地球科學"],["如何判讀地形圖？","地球科學"],["什麼是 DEM？","地球科學"],["Coherence 是什麼？","地球科學"],["時間基線是什麼？","地球科學"],["空間基線是什麼？","地球科學"],["Sentinel-1 衛星介紹","地球科學"],["什麼是 Phase Unwrapping？","地球科學"],["什麼是 LOS 位移？","地球科學"],["GNSS 和 InSAR 如何互相比較？","地球科學"],["如何用 QGIS 做基本地圖？","地球科學"],["如何閱讀一篇科學論文？","學習與研究"],["我的研究主題介紹","學習與研究"],["最近學到的一個新知","學習與研究"],["推薦一本書","生活與興趣"],["推薦一部電影","生活與興趣"],["推薦一個 YouTube 頻道","生活與興趣"],["我最喜歡的一項工具","生活與興趣"],["如何改善口條？","口語表達"],["如何建立自信？","口語表達"],["AI 如何幫助學習？","學習與研究"],["一件改變我想法的事情","生活與興趣"],["如果我要教小學生什麼是地震","口語表達"],["如何用一分鐘介紹自己","口語表達"],["最近的一則新聞","生活與興趣"],["如何培養閱讀習慣","生活與興趣"],["旅行中最難忘的地方","生活與興趣"],["我最想學的一項技能","生活與興趣"],["未來十年的科技趨勢","學習與研究"],["如何用生活比喻解釋資料處理","口語表達"],["為什麼要做研究？","學習與研究"],["如何面對敏感的人","生活與興趣"],["自信和自卑的差別","生活與興趣"],["如何把複雜知識講簡單？","口語表達"],["如何安排一週練口條？","口語表達"],["如何克服錄音時緊張？","口語表達"],["如何用三分鐘介紹一張地圖？","口語表達"],["如何解釋一張 InSAR 干涉圖？","地球科學"],["地下水與地層下陷的關係","地球科學"],["乾旱事件對地表變形的影響","地球科學"],["如何準備研討會海報口說？","口語表達"],["什麼是科普溝通？","口語表達"]],
 audiences:["幼稚園小朋友","國小學生","國中生","高中生","大學生","研究生","完全沒有背景的人","公司主管","教授","媒體記者","面試官","投資人","朋友","長輩","YouTube 觀眾","研討會評審","社團新朋友","第一次聽你報告的人","跨領域同學","國外訪客"],
 styles:["3 分鐘教學","1 分鐘電梯簡報","用比喻說明","用故事開場","假裝對高中生解釋","先講結論再展開","用三個重點整理","假裝在拍 YouTube 影片","假裝新聞主播","用問答方式","用白板／紙筆輔助","用生活例子說明","用正式學術報告風格","用輕鬆聊天方式","用 TED 演講風格","用面試回答方式","用懶人包方式","用反問句開場","用問題—原因—解法結構","用一張圖來講解"],
 constraints:["不能說「然後」","不能說「就是」","必須舉 2 個例子","結尾要有一句總結","開頭 10 秒內講出重點","中間要停頓 2 次","要加入一個數據","要加入一個生活比喻","要問觀眾一個問題","全程站著講","不看任何筆記","最後自問自答 1 題","必須用三段式結構","全程控制語速","每段先講一句重點","要有清楚的開場白","要有清楚的收尾","至少使用一次手勢","避免過度使用口頭禪","講完後立刻錄下自評","要加入一個反例","要用一句話定義主題","要用「為什麼重要」串接","要模擬觀眾提問","要用 30 秒做總結","要減少專有名詞","要把專有名詞翻成白話","要加入一個故事","要講出適用情境","要講出常見誤解","要用條列方式講","要用因果關係講","要用對比法講","要用時間順序講","要用空間順序講","要用問題解決法講","要讓結尾有記憶點","要練習眼神看鏡頭","要刻意放慢開頭","要控制在指定時間內"],
 durations:[['30 秒',30],['1 分鐘',60],['90 秒',90],['2 分鐘',120],['3 分鐘',180],['5 分鐘',300],['7 分鐘',420],['10 分鐘',600]]
};
const $=id=>document.getElementById(id),pick=a=>a[Math.floor(Math.random()*a.length)],STORE='speakingProRecords',FAV='speakingProFavorites';
let challenge,timerId,remaining=0,running=false,recorder,stream,clipBlob,clipUrl;
let audioContext,analyser,monitorId,recordStartedAt=0,signalFrames=[],clipFrames=0,recognition,transcriptText='',lastAnalysis=null;
const localDay=d=>new Date(d).toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'});
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const records=()=>JSON.parse(localStorage.getItem(STORE)||'[]'); const favorites=()=>JSON.parse(localStorage.getItem(FAV)||'[]');
function draw(){const [topic,category]=pick(bank.topics),[duration,seconds]=pick(bank.durations);challenge={topic,category,duration,seconds,audience:pick(bank.audiences),style:pick(bank.styles),constraint:pick(bank.constraints)};['topic','audience','style','duration','constraint'].forEach(k=>$(k).textContent=challenge[k]);$('topic-category').textContent=category;syncStar();resetTimer();}
function syncStar(){const saved=favorites().includes(challenge.topic);$('favorite-topic').textContent=saved?'★':'☆';$('favorite-topic').setAttribute('aria-label',saved?'取消收藏這個主題':'收藏這個主題');}
function toggleFavorite(){let data=favorites();data=data.includes(challenge.topic)?data.filter(x=>x!==challenge.topic):[challenge.topic,...data];localStorage.setItem(FAV,JSON.stringify(data));syncStar();renderAll();}
function resetTimer(){clearInterval(timerId);running=false;remaining=challenge?.seconds||0;$('timer').textContent='開始計時';$('timer-status').textContent='倒數時間會依抽到的指定時間設定。';$('practice-title').textContent=fmt(remaining);}
function toggleTimer(){if(running){clearInterval(timerId);running=false;$('timer').textContent='繼續計時';$('timer-status').textContent='已暫停';return}running=true;$('timer').textContent='暫停';$('timer-status').textContent='練習中';timerId=setInterval(()=>{remaining--; $('practice-title').textContent=fmt(Math.max(0,remaining));if(remaining<=0){clearInterval(timerId);running=false;$('timer').textContent='重新開始';$('timer-status').textContent='時間到，做得好！';navigator.vibrate?.([120,70,120]);}},1000)}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('speakingProAudio',1);req.onupgradeneeded=()=>req.result.createObjectStore('clips');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});}
async function audioPut(id,blob){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('clips','readwrite');tx.objectStore('clips').put(blob,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});}
async function audioGet(id){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('clips');const q=tx.objectStore('clips').get(id);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});}
async function audioDelete(id){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('clips','readwrite');tx.objectStore('clips').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});}
function startSignalMonitor(activeStream){audioContext=new (window.AudioContext||window.webkitAudioContext)();analyser=audioContext.createAnalyser();analyser.fftSize=1024;audioContext.createMediaStreamSource(activeStream).connect(analyser);const values=new Uint8Array(analyser.fftSize);monitorId=setInterval(()=>{analyser.getByteTimeDomainData(values);let sum=0,peak=0;for(const v of values){const n=Math.abs((v-128)/128);sum+=n*n;peak=Math.max(peak,n)}signalFrames.push(Math.sqrt(sum/values.length));if(peak>.96)clipFrames++;},100)}
function stopSignalMonitor(){clearInterval(monitorId);audioContext?.close();audioContext=null;}
function startRecognition(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$('analysis-status').textContent='此瀏覽器不支援自動逐字稿；仍會分析音量與錄音時長。';return}transcriptText='';recognition=new Recognition();recognition.lang='zh-TW';recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let finalText='',interim='';for(let i=0;i<e.results.length;i++){const text=e.results[i][0].transcript;e.results[i].isFinal?finalText+=text:interim+=text}transcriptText=finalText||transcriptText;$('transcript').textContent=transcriptText+(interim?` ${interim}`:'');};recognition.onerror=()=>{$('analysis-status').textContent='逐字稿暫時無法使用；仍會完成本機音量分析。'};try{recognition.start()}catch{}}
function makeAnalysis(){const seconds=Math.max(1,Math.round((Date.now()-recordStartedAt)/1000)),avg=signalFrames.length?signalFrames.reduce((a,b)=>a+b,0)/signalFrames.length:0,clipPct=signalFrames.length?clipFrames/signalFrames.length:0,chars=(transcriptText.match(/[\u4e00-\u9fffA-Za-z0-9]/g)||[]).length,rate=Math.round(chars/seconds*60),fillers=['然後','就是','嗯','呃','那個'],fillerCount=fillers.reduce((n,w)=>n+(transcriptText.match(new RegExp(w,'g'))||[]).length,0);let quality=avg<.015?'音量偏低，靠近麥克風或提高音量。':clipPct>.03?'疑似爆音，離麥克風遠一點或降低音量。':'音量大致穩定。';return{seconds,avg:Math.round(avg*1000)/10,clipPct:Math.round(clipPct*1000)/10,chars,rate,fillerCount,quality,transcript:transcriptText}}
function renderSpeechAnalysis(data){if(!data)return;$('analysis-status').textContent=data.quality;$('quality-metrics').innerHTML=`<div>音量<strong>${data.avg}%</strong></div><div>語速<strong>${data.rate||'—'} 字／分</strong></div><div>口頭禪<strong>${data.fillerCount} 次</strong></div>`;$('transcript').textContent=data.transcript||'此瀏覽器未提供逐字稿；可播放錄音自行回聽。';}
async function toggleRecording(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('record-status').textContent='此瀏覽器不支援錄音功能。';return}if(recorder?.state==='recording'){recorder.stop();return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];signalFrames=[];clipFrames=0;recordStartedAt=Date.now();$('transcript').textContent='正在聆聽…';$('quality-metrics').innerHTML='';$('analysis-status').textContent='正在分析音量與口條…';startSignalMonitor(stream);startRecognition();recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{clipBlob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});if(clipUrl)URL.revokeObjectURL(clipUrl);clipUrl=URL.createObjectURL(clipBlob);$('preview').src=clipUrl;$('preview').hidden=false;$('record').classList.remove('active');$('record').textContent='重新錄音';$('record-status').textContent='錄音完成，儲存紀錄時會一併保留。';stopSignalMonitor();try{recognition?.stop()}catch{};setTimeout(()=>{lastAnalysis=makeAnalysis();renderSpeechAnalysis(lastAnalysis)},200);stream.getTracks().forEach(t=>t.stop())};recorder.start();$('record').classList.add('active');$('record').textContent='停止錄音';$('record-status').textContent='正在錄音…';}catch(err){$('record-status').textContent=err.name==='NotAllowedError'?'未取得麥克風權限。請在瀏覽器允許麥克風。':'無法開始錄音。'}}
async function savePractice(e){e.preventDefault();const id=crypto.randomUUID();const item={id,...challenge,status:$('status').value,rating:$('rating').value,note:$('note').value.trim(),createdAt:new Date().toISOString(),hasAudio:!!clipBlob,speechAnalysis:lastAnalysis};if(clipBlob)await audioPut(id,clipBlob);localStorage.setItem(STORE,JSON.stringify([item,...records()]));e.target.reset();$('rating').value='3';clipBlob=null;lastAnalysis=null;$('preview').hidden=true;$('record-status').textContent='按下後允許麥克風權限';$('analysis-status').textContent='錄音後會顯示音量、語速與口頭禪統計。';$('quality-metrics').innerHTML='';$('transcript').textContent='尚未開始錄音。';renderAll();$('save-title').textContent='已儲存！';setTimeout(()=>$('save-title').textContent='把這次練習留下來',1500);}
function stats(){const done=records().filter(x=>x.status==='已完成'),days=[...new Set(done.map(x=>localDay(x.createdAt)))].sort().reverse();let streak=0,day=new Date();while(days.includes(localDay(day))){streak++;day.setDate(day.getDate()-1)}return{done,streak}}
function renderMetrics(){const {done,streak}=stats();$('total-count').textContent=done.length;$('streak-count').textContent=`${streak} 天`;$('favorite-count').textContent=favorites().length;$('streak-note').textContent=streak?`已連續練習 ${streak} 天`:'今天完成一次即可開始累積';}
function renderBadges(){const n=stats().done.length,items=[[1,'🌱','首次完成'],[7,'🔥','完成 7 次'],[30,'🎯','完成 30 次'],[100,'🏆','完成 100 次']];$('badges').innerHTML=items.map(([need,icon,label])=>`<article class="badge ${n>=need?'unlocked':''}"><span class="emoji">${icon}</span><b>${label}</b><small>${n>=need?'已解鎖':`${n}/${need}`}</small></article>`).join('');}
function renderAnalysis(){const done=stats().done,allCats=[...new Set(bank.topics.map(x=>x[1]))],counts=Object.fromEntries(allCats.map(x=>[x,0]));done.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);const max=Math.max(1,...Object.values(counts));$('category-chart').innerHTML=allCats.map(c=>`<div class="chart-row"><span>${c}</span><div class="bar"><span style="width:${counts[c]/max*100}%"></span></div><b>${counts[c]}</b></div>`).join('');$('analysis-note').textContent=done.length?`目前最多：${allCats.sort((a,b)=>counts[b]-counts[a])[0]}；最少：${allCats.sort((a,b)=>counts[a]-counts[b])[0]}。`:'完成練習後，這裡會顯示類別分布。'}
function renderFavorites(){const data=favorites();$('favorites').innerHTML=data.length?data.map(t=>`<div class="list-item"><span>${t}</span><button class="link-button" data-unfavorite="${encodeURIComponent(t)}">移除</button></div>`).join(''):'<p class="muted">點主題旁的 ☆ 收藏常想練習的題目。</p>';document.querySelectorAll('[data-unfavorite]').forEach(b=>b.onclick=()=>{const t=decodeURIComponent(b.dataset.unfavorite);localStorage.setItem(FAV,JSON.stringify(favorites().filter(x=>x!==t)));syncStar();renderAll()})}
function renderHistory(){const data=records().slice(0,20);$('history').innerHTML=data.length?data.map(x=>`<article class="history-item"><div class="history-meta"><span>${new Date(x.createdAt).toLocaleString('zh-TW')}</span><span>${x.status} · ${x.rating} 分</span></div><h3>${x.topic}</h3><p>${x.category}｜${x.audience}｜${x.style}｜${x.duration}</p>${x.note?`<p>下次改進：${x.note}</p>`:''}${x.speechAnalysis?`<p>口條分析：${x.speechAnalysis.rate||'—'} 字／分、口頭禪 ${x.speechAnalysis.fillerCount} 次。${x.speechAnalysis.quality}</p>`:''}${x.hasAudio?`<div class="audio-actions"><button data-play="${x.id}">播放錄音</button><a data-download="${x.id}" href="#">下載音檔</a><button data-delete-audio="${x.id}">刪除錄音</button></div>`:''}</article>`).join(''):'<p class="muted">尚無紀錄。完成一組挑戰後，統計與徽章會開始累積。</p>';document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playAudio(b.dataset.play));document.querySelectorAll('[data-download]').forEach(b=>b.onclick=e=>downloadAudio(e,b));document.querySelectorAll('[data-delete-audio]').forEach(b=>b.onclick=e=>downloadAudio(e,b));document.querySelectorAll('[data-delete-audio]').forEach(b=>b.onclick=()=>removeAudio(b.dataset.deleteAudio));}
async function playAudio(id){const blob=await audioGet(id);if(!blob)return alert('找不到此錄音，可能已被瀏覽器清除。');const a=new Audio(URL.createObjectURL(blob));a.play();}async function downloadAudio(e,b){e.preventDefault();const blob=await audioGet(b.dataset.download);if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`口條練習-${b.dataset.download}.webm`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}async function removeAudio(id){if(!confirm('確定刪除這段錄音嗎？'))return;await audioDelete(id);const all=records().map(x=>x.id===id?{...x,hasAudio:false}:x);localStorage.setItem(STORE,JSON.stringify(all));renderHistory()}
function renderAll(){renderMetrics();renderBadges();renderAnalysis();renderFavorites();renderHistory();}
document.querySelector('#today').textContent=new Intl.DateTimeFormat('zh-TW',{dateStyle:'full'}).format(new Date());$('draw').onclick=draw;$('favorite-topic').onclick=toggleFavorite;$('timer').onclick=toggleTimer;$('timer-reset').onclick=resetTimer;$('record').onclick=toggleRecording;$('practice-form').onsubmit=savePractice;$('clear-data').onclick=async()=>{if(confirm('確定清除所有練習紀錄、收藏與錄音嗎？')){localStorage.removeItem(STORE);localStorage.removeItem(FAV);indexedDB.deleteDatabase('speakingProAudio');renderAll();syncStar();}};draw();renderAll();
